const Languages = {
  _text: [
    {display: 'Afrikaans', code: 'af'},
    {display: 'Albanian', code: 'sq'},
    {display: 'Amharic', code: 'am'},
    {display: 'Arabic', code: 'ar'},
    {display: 'Armenian', code: 'hy'},
    {display: 'Azerbaijani', code: 'az'},
    {display: 'Basque', code: 'eu'},
    {display: 'Belarusian', code: 'be'},
    {display: 'Bengali', code: 'bn'},
    {display: 'Bosnian', code: 'bs'},
    {display: 'Bulgarian', code: 'bg'},
    {display: 'Catalan', code: 'ca'},
    {display: 'Cebuano', code: 'ceb'},
    {display: 'Chinese (Simplified)', code: 'zh-CN', tld: 'hk'},
    {display: 'Chinese (Traditional)', code: 'zh-TW', tld: 'hk'},
    {display: 'Corsican', code: 'co'},
    {display: 'Croatian', code: 'hr'},
    {display: 'Czech', code: 'cs'},
    {display: 'Danish', code: 'da'},
    {display: 'Dutch', code: 'nl'},
    {display: 'English', code: 'en', tld: 'com'},
    {display: 'Esperanto', code: 'eo'},
    {display: 'Estonian', code: 'et'},
    {display: 'Finnish', code: 'fi'},
    {display: 'French', code: 'fr'},
    {display: 'Frisian', code: 'fy'},
    {display: 'Galician', code: 'gl'},
    {display: 'Georgian', code: 'ka'},
    {display: 'German', code: 'de'},
    {display: 'Greek', code: 'el'},
    {display: 'Gujarati', code: 'gu'},
    {display: 'Haitian Creole', code: 'ht'},
    {display: 'Hausa', code: 'ha'},
    {display: 'Hawaiian', code: 'haw'},
    {display: 'Hebrew', code: 'iw'},
    {display: 'Hindi', code: 'hi'},
    {display: 'Hmong', code: 'hmn'},
    {display: 'Hungarian', code: 'hu'},
    {display: 'Icelandic', code: 'is'},
    {display: 'Igbo', code: 'ig'},
    {display: 'Indonesian', code: 'id'},
    {display: 'Irish', code: 'ga'},
    {display: 'Italian', code: 'it'},
    {display: 'Japanese', code: 'ja'},
    {display: 'Javanese', code: 'jw'},
    {display: 'Kannada', code: 'kn'},
    {display: 'Kazakh', code: 'kk'},
    {display: 'Khmer', code: 'km'},
    {display: 'Korean', code: 'ko'},
    {display: 'Kurdish', code: 'ku'},
    {display: 'Kyrgyz', code: 'ky'},
    {display: 'Lao', code: 'lo'},
    {display: 'Latin', code: 'la'},
    {display: 'Latvian', code: 'lv'},
    {display: 'Lithuanian', code: 'lt'},
    {display: 'Luxembourgish', code: 'lb'},
    {display: 'Macedonian', code: 'mk'},
    {display: 'Malagasy', code: 'mg'},
    {display: 'Malay', code: 'ms'},
    {display: 'Malayalam', code: 'ml'},
    {display: 'Maltese', code: 'mt'},
    {display: 'Maori', code: 'mi'},
    {display: 'Marathi', code: 'mr'},
    {display: 'Mongolian', code: 'mn'},
    {display: 'Myanmar (Burmese)', code: 'my'},
    {display: 'Nepali', code: 'ne'},
    {display: 'Norwegian', code: 'no'},
    {display: 'Nyanja (Chichewa)', code: 'ny'},
    {display: 'Pashto', code: 'ps'},
    {display: 'Persian', code: 'fa'},
    {display: 'Polish', code: 'pl'},
    {display: 'Portuguese (Portugal, Brazil)', code: 'pt'},
    {display: 'Punjabi', code: 'pa'},
    {display: 'Romanian', code: 'ro'},
    {display: 'Russian', code: 'ru'},
    {display: 'Samoan', code: 'sm'},
    {display: 'Scots Gaelic', code: 'gd'},
    {display: 'Serbian', code: 'sr'},
    {display: 'Sesotho', code: 'st'},
    {display: 'Shona', code: 'sn'},
    {display: 'Sindhi', code: 'sd'},
    {display: 'Sinhala (Sinhalese)', code: 'si'},
    {display: 'Slovak', code: 'sk'},
    {display: 'Slovenian', code: 'sl'},
    {display: 'Somali', code: 'so'},
    {display: 'Spanish', code: 'es'},
    {display: 'Sundanese', code: 'su'},
    {display: 'Swahili', code: 'sw'},
    {display: 'Swedish', code: 'sv', tld: 'se'},
    {display: 'Tagalog (Filipino)', code: 'tl'},
    {display: 'Tajik', code: 'tg'},
    {display: 'Tamil', code: 'ta'},
    {display: 'Telugu', code: 'te'},
    {display: 'Thai', code: 'th'},
    {display: 'Turkish', code: 'tr'},
    {display: 'Ukrainian', code: 'uk'},
    {display: 'Urdu', code: 'ur'},
    {display: 'Uzbek', code: 'uz'},
    {display: 'Vietnamese', code: 'vi'},
    {display: 'Welsh', code: 'cy'},
    {display: 'Xhosa', code: 'xh'},
    {display: 'Yiddish', code: 'yi'},
    {display: 'Yoruba', code: 'yo'},
    {display: 'Zulu', code: 'zu'},
  ],

  _sound: [
    {display: 'Afrikaans (South Africa)', code: 'af-ZA'},
    {display: 'Amharic (Ethiopia)', code: 'am-ET'},
    {display: 'Arabic (Algeria)', code: 'ar-DZ'},
    {display: 'Arabic (Bahrain)', code: 'ar-BH'},
    {display: 'Arabic (Egypt)', code: 'ar-EG'},
    {display: 'Arabic (Iraq)', code: 'ar-IQ'},
    {display: 'Arabic (Israel)', code: 'ar-IL'},
    {display: 'Arabic (Jordan)', code: 'ar-JO'},
    {display: 'Arabic (Kuwait)', code: 'ar-KW'},
    {display: 'Arabic (Lebanon)', code: 'ar-LB'},
    {display: 'Arabic (Morocco)', code: 'ar-MA'},
    {display: 'Arabic (Oman)', code: 'ar-OM'},
    {display: 'Arabic (Qatar)', code: 'ar-QA'},
    {display: 'Arabic (Saudi Arabia)', code: 'ar-SA'},
    {display: 'Arabic (State of Palestine)', code: 'ar-PS'},
    {display: 'Arabic (Tunisia)', code: 'ar-TN'},
    {display: 'Arabic (United Arab Emirates)', code: 'ar-AE'},
    {display: 'Armenian (Armenia)', code: 'hy-AM'},
    {display: 'Azerbaijani (Azerbaijan)', code: 'az-AZ'},
    {display: 'Basque (Spain)', code: 'eu-ES'},
    {display: 'Bengali (Bangladesh)', code: 'bn-BD'},
    {display: 'Bengali (India)', code: 'bn-IN'},
    {display: 'Bulgarian (Bulgaria)', code: 'bg-BG'},
    {display: 'Catalan (Spain)', code: 'ca-ES'},
    {display: 'Chinese, Cantonese (Traditional, Hong Kong)', code: 'yue-Hant-HK', tld: 'hk'},
    {display: 'Chinese, Mandarin (Simplified, China)', code: 'zh', tld: 'cn'},
    {display: 'Chinese, Mandarin (Simplified, Hong Kong)', code: 'zh-HK', tld: 'hk'},
    {display: 'Chinese, Mandarin (Traditional, Taiwan)', code: 'zh-TW', tld: 'hk'},
    {display: 'Croatian (Croatia)', code: 'hr-HR'},
    {display: 'Czech (Czech Republic)', code: 'cs-CZ'},
    {display: 'Danish (Denmark)', code: 'da-DK'},
    {display: 'Dutch (Netherlands)', code: 'nl-NL'},
    {display: 'English (Australia)', code: 'en-AU', tld: 'com'},
    {display: 'English (Canada)', code: 'en-CA', tld: 'com'},
    {display: 'English (Ghana)', code: 'en-GH', tld: 'com'},
    {display: 'English (India)', code: 'en-IN', tld: 'com'},
    {display: 'English (Ireland)', code: 'en-IE', tld: 'com'},
    {display: 'English (Kenya)', code: 'en-KE', tld: 'com'},
    {display: 'English (New Zealand)', code: 'en-NZ', tld: 'com'},
    {display: 'English (Nigeria)', code: 'en-NG', tld: 'com'},
    {display: 'English (Philippines)', code: 'en-PH', tld: 'com'},
    {display: 'English (Singapore)', code: 'en-SG', tld: 'com'},
    {display: 'English (South Africa)', code: 'en-ZA', tld: 'com'},
    {display: 'English (Tanzania)', code: 'en-TZ', tld: 'com'},
    {display: 'English (United Kingdom)', code: 'en-GB', tld: 'com'},
    {display: 'English (United States)', code: 'en-US', tld: 'com'},
    {display: 'Filipino (Philippines)', code: 'fil-PH'},
    {display: 'Finnish (Finland)', code: 'fi-FI'},
    {display: 'French (Canada)', code: 'fr-CA'},
    {display: 'French (France)', code: 'fr-FR'},
    {display: 'Galician (Spain)', code: 'gl-ES'},
    {display: 'Georgian (Georgia)', code: 'ka-GE'},
    {display: 'German (Germany)', code: 'de-DE'},
    {display: 'Greek (Greece)', code: 'el-GR'},
    {display: 'Gujarati (India)', code: 'gu-IN'},
    {display: 'Hebrew (Israel)', code: 'he-IL'},
    {display: 'Hindi (India)', code: 'hi-IN'},
    {display: 'Hungarian (Hungary)', code: 'hu-HU'},
    {display: 'Icelandic (Iceland)', code: 'is-IS'},
    {display: 'Indonesian (Indonesia)', code: 'id-ID'},
    {display: 'Italian (Italy)', code: 'it-IT'},
    {display: 'Japanese (Japan)', code: 'ja-JP'},
    {display: 'Javanese (Indonesia)', code: 'jv-ID'},
    {display: 'Kannada (India)', code: 'kn-IN'},
    {display: 'Khmer (Cambodia)', code: 'km-KH'},
    {display: 'Korean (South Korea)', code: 'ko-KR'},
    {display: 'Lao (Laos)', code: 'lo-LA'},
    {display: 'Latvian (Latvia)', code: 'lv-LV'},
    {display: 'Lithuanian (Lithuania)', code: 'lt-LT'},
    {display: 'Malay (Malaysia)', code: 'ms-MY'},
    {display: 'Malayalam (India)', code: 'ml-IN'},
    {display: 'Marathi (India)', code: 'mr-IN'},
    {display: 'Nepali (Nepal)', code: 'ne-NP'},
    {display: 'Norwegian Bokmål (Norway)', code: 'nb-NO'},
    {display: 'Persian (Iran)', code: 'fa-IR'},
    {display: 'Polish (Poland)', code: 'pl-PL'},
    {display: 'Portuguese (Brazil)', code: 'pt-BR'},
    {display: 'Portuguese (Portugal)', code: 'pt-PT'},
    {display: 'Romanian (Romania)', code: 'ro-RO'},
    {display: 'Russian (Russia)', code: 'ru-RU'},
    {display: 'Serbian (Serbia)', code: 'sr-RS'},
    {display: 'Sinhala (Sri Lanka)', code: 'si-LK'},
    {display: 'Slovak (Slovakia)', code: 'sk-SK'},
    {display: 'Slovenian (Slovenia)', code: 'sl-SI'},
    {display: 'Spanish (Argentina)', code: 'es-AR'},
    {display: 'Spanish (Bolivia)', code: 'es-BO'},
    {display: 'Spanish (Chile)', code: 'es-CL'},
    {display: 'Spanish (Colombia)', code: 'es-CO'},
    {display: 'Spanish (Costa Rica)', code: 'es-CR'},
    {display: 'Spanish (Dominican Republic)', code: 'es-DO'},
    {display: 'Spanish (Ecuador)', code: 'es-EC'},
    {display: 'Spanish (El Salvador)', code: 'es-SV'},
    {display: 'Spanish (Guatemala)', code: 'es-GT'},
    {display: 'Spanish (Honduras)', code: 'es-HN'},
    {display: 'Spanish (Mexico)', code: 'es-MX'},
    {display: 'Spanish (Nicaragua)', code: 'es-NI'},
    {display: 'Spanish (Panama)', code: 'es-PA'},
    {display: 'Spanish (Paraguay)', code: 'es-PY'},
    {display: 'Spanish (Peru)', code: 'es-PE'},
    {display: 'Spanish (Puerto Rico)', code: 'es-PR'},
    {display: 'Spanish (Spain)', code: 'es-ES'},
    {display: 'Spanish (United States)', code: 'es-US'},
    {display: 'Spanish (Uruguay)', code: 'es-UY'},
    {display: 'Spanish (Venezuela)', code: 'es-VE'},
    {display: 'Sundanese (Indonesia)', code: 'su-ID'},
    {display: 'Swahili (Kenya)', code: 'sw-KE'},
    {display: 'Swahili (Tanzania)', code: 'sw-TZ'},
    {display: 'Swedish (Sweden)', code: 'sv-SE', tld: 'se'},
    {display: 'Tamil (India)', code: 'ta-IN'},
    {display: 'Tamil (Malaysia)', code: 'ta-MY'},
    {display: 'Tamil (Singapore)', code: 'ta-SG'},
    {display: 'Tamil (Sri Lanka)', code: 'ta-LK'},
    {display: 'Telugu (India)', code: 'te-IN'},
    {display: 'Thai (Thailand)', code: 'th-TH'},
    {display: 'Turkish (Turkey)', code: 'tr-TR'},
    {display: 'Ukrainian (Ukraine)', code: 'uk-UA'},
    {display: 'Urdu (India)', code: 'ur-IN'},
    {display: 'Urdu (Pakistan)', code: 'ur-PK'},
    {display: 'Vietnamese (Vietnam)', code: 'vi-VN'},
    {display: 'Zulu (South Africa)', code: 'zu-ZA'},
  ],

  translate: {
    choices: () => Languages._text,
    display: (code) => Languages.translate.choices().find((x) => x.code === code).display,
    tld: (code) => Languages.translate.choices().find((x) => x.code === code).tld ?? 'com',
 },

  translatePage: {
    choices: () => Languages._text,
    display: (code) => Languages.translatePage.choices().find((x) => x.code === code).display,
    tld: (code) => Languages.translatePage.choices().find((x) => x.code === code).tld ?? 'com',
 },

  tts: {
    choices: () => Languages._sound,
    display: (code) => Languages.tts.choices().find((x) => x.code === code).display,
    tld: (code) => Languages.tts.choices().find((x) => x.code === code).tld ?? 'com',
 },
};
